In [1]:
# Import all libraries

In [2]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score

#  Read the value

We will store the data in a variable **digit**

In [13]:
digit=pd.read_csv("train.csv")
test=pd.read_csv("test.csv")

In [14]:
digit.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [15]:
digit.isnull().any().any()

False

In [16]:
y=digit.label.values
del digit['label']
print y

[1 0 1 ..., 7 6 9]


Since, there are many features.We have to reduce no of features.Otherwise, there will be curse of dimensionality.

In [20]:
x=np.concatenate((digit.values,test.values),axis=0)
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [23]:
# test=x[42000:]
# test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [24]:
print len(test)

28000


In [25]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ..., 
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [26]:
pca = PCA(n_components=80)
X = pca.fit_transform(x)

In [27]:
print pca.explained_variance_ratio_.sum()

0.891030437299


In [28]:
pca.explained_variance_ratio_*100

array([ 9.74611592,  7.15544459,  6.14953098,  5.40338453,  4.8889337 ,
        4.30522703,  3.27826152,  2.88964157,  2.7583642 ,  2.34214017,
        2.10668855,  2.03755324,  1.7070643 ,  1.69401978,  1.58338224,
        1.4863449 ,  1.31935849,  1.27901425,  1.18727249,  1.1529367 ,
        1.06603978,  1.00979434,  0.95915123,  0.90963508,  0.88328682,
        0.83881821,  0.80983179,  0.7857179 ,  0.74026223,  0.69001416,
        0.65614399,  0.64547029,  0.6008193 ,  0.58561175,  0.56675356,
        0.54347066,  0.50471707,  0.48707942,  0.47895514,  0.46759365,
        0.45436863,  0.44491801,  0.4182166 ,  0.39616391,  0.38370775,
        0.3757848 ,  0.36142628,  0.3490246 ,  0.3387316 ,  0.31969617,
        0.31685403,  0.31014491,  0.29648035,  0.28710145,  0.2825138 ,
        0.26942271,  0.26839231,  0.25650934,  0.25316785,  0.24464803,
        0.23970224,  0.238581  ,  0.22923375,  0.22094899,  0.21306047,
        0.20631746,  0.20278138,  0.19503512,  0.19147063,  0.18

In [29]:
X

array([[  675.62550913,   682.91580793,  -186.49864016, ...,
          -12.30988597,   -31.21493698,    44.12342093],
       [-1690.62513538,   402.06826604,   488.58511533, ...,
         -137.3344343 ,  -103.84897689,   -22.99855128],
       [  890.13111336,   275.55956267,   -79.44272042, ...,
          -14.17181832,    18.70999833,     9.31065312],
       ..., 
       [  138.40587705,   644.81877827,   880.68880607, ...,
          -57.91748406,    62.73899496,   -70.21589852],
       [   49.43276834,  -578.10899532,   323.9904944 , ...,
           12.10522672,    14.31675276,    39.23375561],
       [ -597.31312568,  -141.72661007,  -818.14854751, ...,
          -26.01666294,     2.51715515,    96.191327  ]])

In [30]:
# print len(X[0])
# print (len(X))

In [31]:
df=pd.DataFrame()
for i in range(pca.explained_variance_ratio_.shape[0]):
    df["pc%i" % (i+1)] = X[:,i]
df.head()

pc1         pc2         pc3         pc4         pc5         pc6  \
0   675.625509  682.915808 -186.498640  127.289953  -78.365677  488.125117   
1 -1690.625135  402.068266  488.585115  346.731780 -453.005179  737.156898   
2   890.131113  275.559563  -79.442720   72.924640 -471.184005 -334.469890   
3   158.531459 -302.925905   66.531553  766.136173 -425.946836  150.842902   
4 -1908.674338  492.370459  525.761544  203.054935 -663.649909  990.467203   

          pc7         pc8         pc9        pc10    ...           pc71  \
0 -692.041655   82.896481 -327.166953  203.119568    ...     -99.011923   
1  662.036984 -181.674905    4.001588   67.466851    ...     -59.783657   
2  438.114151 -297.464086  196.553054  -20.046388    ...      53.957096   
3 -299.858993  276.099877   57.491297 -286.775435    ...       4.412093   
4  572.753923 -256.950735 -127.437184  176.518499    ...      99.465896   

        pc72        pc73       pc74        pc75       pc76        pc77  \
0  -1.717132  -19.135171 -50.475933  111.340047 -19.344636  -14.593009   
1 -19.697370  -98.436921   3.423161  -83.530015   9.847579 -101.914037   
2 -74.773142   58.578968 -25.821295  -41.283994  74.355378   -6.553371   
3  73.929116  -17.712819  56.063024   16.995985  41.265905   25.719293   
4 -68.096098 -243.713193 -26.943923  -70.271807 -44.691376    5.394058   

         pc78        pc79       pc80  
0  -12.309886  -31.214937  44.123421  
1 -137.334434 -103.848977 -22.998551  
2  -14.171818   18.709998   9.310653  
3   10.468135  -46.750102  91.180250  
4  -33.713446  -13.636052 -68.566914  

[5 rows x 80 columns]

In [35]:
test=df[42000:]

In [38]:
df=df[:42000]
len(df)

42000

In [39]:
df['digit']=y

/home/abhijeet/anaconda3/envs/py27/lib/python2.7/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':


In [42]:
y=df['digit'].values
y

array([1, 0, 1, ..., 7, 6, 9])

In [43]:
del df['digit']

Now we have to make the model 

Split data for cross validation 

In [44]:
Xtrain, Xcv, ytrain, ycv = train_test_split(df.values, y, train_size=0.80)

In [45]:
print (Xtrain)

[[  108.75213312  -190.59845323   864.83496958 ...,   -41.42858667
    -43.96366038   -16.43424022]
 [  614.03701368  -485.2051311   -150.13895545 ...,    30.69630108
      2.75674415   -33.83271431]
 [   48.37983379   450.56540916  -263.81941101 ...,    10.21827782
    -44.70841105   -21.55813534]
 ..., 
 [  977.90163688   409.73179677  -100.37886513 ...,    29.0434478
     12.1162582     21.30555412]
 [  -30.75072906  -843.18253428  -310.65077289 ...,   101.76508666
     21.10937828    23.84775219]
 [ -217.07118382   443.46143098  1103.0312477  ...,    23.57646236
    -33.91623911    22.39531293]]


In [46]:
clf= KNeighborsClassifier(10)
print clf

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=10, p=2,
           weights='uniform')


In [47]:
clf=clf.fit(Xtrain, ytrain)

In [48]:
training_accuracy = clf.score(Xtrain, ytrain)

In [49]:
test_accuracy = clf.score(Xcv, ycv)
print (training_accuracy,test_accuracy)

(0.97538690476190482, 0.9653571428571428)


In [50]:
Xall=np.concatenate((Xtrain, Xcv))
Yall=np.concatenate((ytrain,ycv))

In [51]:
predict=clf.predict(Xall)

In [56]:
Yall

array([5, 4, 3, ..., 8, 8, 2])

In [52]:
predict

array([5, 4, 3, ..., 8, 8, 2])

In [53]:
accuracy_score(Yall, predict)

0.97338095238095235

In [35]:
test=pd.read_csv("test.csv")

In [39]:
pca = PCA(n_components=80)
X = pca.fit_transform(test.values)

In [54]:
test

pc1          pc2          pc3          pc4         pc5  \
42000  -845.662350   130.182274  -776.849293   645.536224  338.498098   
42001 -1150.060109    42.099132  -210.676463   -93.959362 -953.848152   
42002   503.627068  -107.753933  -167.663214   -85.295174 -169.299056   
42003   254.287072  -595.593071  -479.099028   404.098852 -228.083008   
42004   107.762966   709.533906   -12.856065   153.405248  284.114520   
42005   262.347141  -778.839810   270.090941    46.190625 -278.040562   
42006 -1712.356550   488.958575  -604.983338  -447.133143 -479.986076   
42007  -241.050356   647.051788   251.527501  -426.852559  489.309701   
42008 -1223.538392   405.366936   191.715198  -302.965193 -995.633399   
42009   -45.086629   635.334632   438.638639  -231.542393 -129.020428   
42010  -274.719823   313.034690   782.745388  -525.661069  147.399617   
42011   416.007087  -129.837432  -132.239503     1.348830 -201.987906   
42012   140.463532  -515.292000   662.856513  -275.405494  240.321136   
42013 -1599.517650   533.336087   377.519709   -35.964443 -855.207645   
42014   -56.900009  -736.335238   274.706992   465.847072 -143.929019   
42015 -1167.898226   752.714662   505.979497  -529.795152   56.705245   
42016  -165.050840   459.081633   380.825380   412.140078 -458.191179   
42017   820.327287   190.922003   132.509507   237.215199 -678.219501   
42018   269.921307  -581.156424   669.429903  -413.871831  397.641335   
42019 -1157.446745   317.025064   416.222131   292.124663 -387.525515   
42020    75.654714  -837.102236   420.586673  -135.847638   45.074640   
42021   956.095414   490.737953   -71.985268   129.149290 -481.330226   
42022   548.268524   366.262604  -408.364141   199.897325  177.987233   
42023   424.524453   213.627116  -333.302596  -347.281851 -628.811237   
42024   216.199464 -1003.580300   349.823732  -589.413691  -59.233759   
42025   556.057623  -354.622383   158.227199  -144.310639   90.810542   
42026  -388.271755   253.868131  -582.811212   599.830809  744.411085   
42027  -748.232180  -954.364282   559.005869  -305.285787 -481.272896   
42028   703.965068   -91.895194  -205.761274  -310.205567  -81.080165   
42029   422.044337  -488.973008  -171.550630  -460.276407  181.516108   
...            ...          ...          ...          ...         ...   
69970  -333.227768  -200.509859   143.891792 -1037.077751 -119.397098   
69971  -911.062894  -531.178232  -699.963706   454.078860 -693.812146   
69972   145.223700  -685.260792  -564.848544   460.143828 -184.948803   
69973 -1108.504808   270.578361   642.634414   -54.587785  651.977990   
69974 -1287.211393   462.495657  -369.448376  -319.167981 -281.141645   
69975  -656.826499   343.312415    28.628056 -1060.984696  618.643788   
69976  -313.111186   169.420051  -788.943051   462.093354  390.840983   
69977 -1239.138063   738.123081  -254.361694  -313.855676 -952.689242   
69978   981.230051   431.556210   -64.275474    70.903412 -391.963285   
69979    79.363630  -342.269548  -800.550850  -423.648040  120.184098   
69980   -30.315792   228.422305  -204.143165  -462.710299 -318.712117   
69981   860.953276   435.400790  -239.949079   232.824988 -222.971607   
69982   465.447004   620.750381  -374.334626   226.197672 -329.422814   
69983  -525.205960  -121.007545   358.485260   188.042269 -259.760556   
69984   274.213641  -303.318221   -48.004556   312.463302  241.181498   
69985 -1057.145339   317.068043   713.193666  -622.487074   16.155129   
69986  -894.237112   -22.319601 -1102.667097   442.347903  493.051134   
69987  -135.356683    63.644232     6.930707   942.469307  679.150092   
69988   623.893327   251.929094  -475.753486  -216.184332   73.948901   
69989  -316.798223   279.883194  -428.609089   412.544441  -61.586730   
69990    61.744864  -874.601456   381.017838  -469.080226 -251.828929   
69991  -408.190461   502.450553  -920.102512   -26.958824  533.325716   
69992   760.001886   248.851917    77.558273   280.490424 -703.590809   


In [55]:
predict=clf.predict(test.values)

In [57]:
test.index.values

array([42000, 42001, 42002, ..., 69997, 69998, 69999])

In [58]:
result = {}
result["ImageId"]=test.index.values
result["Label"]=predict
print result

{'Label': array([2, 0, 9, ..., 3, 9, 2]), 'ImageId': array([42000, 42001, 42002, ..., 69997, 69998, 69999])}


In [59]:
from pandas import Series, DataFrame
result = DataFrame(result,columns=['ImageId','Label'])
print result

       ImageId  Label
0        42000      2
1        42001      0
2        42002      9
3        42003      9
4        42004      3
5        42005      7
6        42006      0
7        42007      3
8        42008      0
9        42009      3
10       42010      5
11       42011      7
12       42012      4
13       42013      0
14       42014      4
15       42015      3
16       42016      3
17       42017      1
18       42018      9
19       42019      0
20       42020      9
21       42021      1
22       42022      1
23       42023      5
24       42024      7
25       42025      4
26       42026      2
27       42027      7
28       42028      9
29       42029      7
...        ...    ...
27970    69970      5
27971    69971      0
27972    69972      4
27973    69973      8
27974    69974      0
27975    69975      3
27976    69976      6
27977    69977      0
27978    69978      1
27979    69979      9
27980    69980      3
27981    69981      1
27982    69982      1
27983    6

In [60]:
result.to_csv('model_output.csv')